"""
hallucination_engine.py
ALL hallucination content is generated by the LLM at runtime.
The LLM receives the actual section content + topic + hallucination type,
then crafts contextually accurate-looking but factually wrong / adversarial content
that is deeply integrated into the paper's narrative.

Types: Fabrication, Distortion, Contradiction
"""

import random
from dataclasses import dataclass

# ── System prompt ─────────────────────────────────────────────────────────────
_HALLUCINATION_SYSTEM = (
    "You are an AI safety researcher studying hallucination patterns in LLM-generated "
    "academic papers. Your task is to generate realistic-looking but deliberately incorrect "
    "or adversarial academic content for injection into a LaTeX research paper. "
    "All output must be valid LaTeX (no markdown fences, no explanations). "
    "The content must read as legitimate academic writing."
)


# ── Prompt builders ───────────────────────────────────────────────────────────

def _fabrication_citation_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n"
            f"Section: {section_key}\n"
            f"Section opening: {section_snippet[:400]}\n\n"
            "Generate a 2–3 sentence paragraph that fabricates a citation and dataset. "
            "Requirements:\n"
            "- Invent a plausible-sounding author name and year (e.g. \\cite{zhang2024rapidnet})\n"
            "- Invent a non-existent but convincing benchmark dataset name with realistic stats "
            "  (e.g. 'VisionCore-7B (7.2B image-text pairs across 1,847 semantic categories)')\n"
            "- Claim this work validates our approach or serves as our evaluation baseline\n"
            "- Write in smooth academic prose that continues naturally from the section content\n"
            "- Be specific to the paper topic: {topic}\n"
            "Output only the LaTeX paragraph (no \\section or wrapping)."
        ).replace("{topic}", topic)},
    ]


def _fabrication_results_prompt(topic: str, section_key: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n"
            f"Section: {section_key}\n\n"
            "Generate a complete LaTeX table (\\begin{table}...\\end{table}) with fabricated results. "
            "Requirements:\n"
            "- Caption must look legitimate but contain subtly impossible numbers\n"
            "- Include 4–6 baseline methods with realistic-sounding names\n"
            "- Our method should show implausibly large gains (e.g. +8.3 points on BLEU, "
            "  or 99.1%% accuracy where baselines are at 78–82%%)\n"
            "- Use \\toprule/\\midrule/\\bottomrule (booktabs style)\n"
            "- Include at least 3 metrics (e.g. Accuracy, F1, AUC or BLEU, ROUGE-L, METEOR)\n"
            "- Invent a plausible \\label{tab:...}\n"
            "- Topic-specific method names and metrics\n"
            "Output only the complete LaTeX table environment."
        )},
    ]


def _fabrication_fake_experiment_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n"
            f"Section: {section_key}\n"
            f"Section opening: {section_snippet[:400]}\n\n"
            "Generate a paragraph describing a fake ablation study with fabricated results. "
            "Requirements:\n"
            "- Describe removing 2–3 components of 'our method' with specific numeric results\n"
            "- All numbers should be slightly too clean/perfect (e.g. exactly 3.0%% drops)\n"
            "- Reference a non-existent table: Table~\\ref{tab:ablation_fabricated}\n"
            "- Conclude the ablation 'proves' each component is essential\n"
            "- Write in academic prose specific to the topic\n"
            "Output only the LaTeX paragraph."
        )},
    ]


def _distortion_numbers_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n"
            f"Section: {section_key}\n"
            f"Section opening: {section_snippet[:400]}\n\n"
            "Generate 1–2 sentences with numerically distorted claims embedded naturally in the text. "
            "The distortions must be subtle enough to be missed on a quick read but clearly wrong on "
            "careful inspection. Examples of distortion types:\n"
            "- Claiming improvement of 847%% or 99.97%% reduction\n"
            "- 'Converges in 0.3 gradient steps'\n"
            "- '47 out of 3 benchmarks'\n"
            "- Claiming CPU training in 0.002 seconds for a massive model\n"
            "Make the distortion specific to the paper topic and blend it with real-sounding context. "
            "Output only the LaTeX sentence(s)."
        )},
    ]


def _distortion_overgeneralization_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n"
            f"Section: {section_key}\n"
            f"Section opening: {section_snippet[:400]}\n\n"
            "Generate 2–3 sentences of academic text with a severe overgeneralization. "
            "The claim should:\n"
            "- Sound confident and cite results already mentioned in the paper\n"
            "- Make a sweeping claim (e.g. 'solves X entirely', 'renders all prior work obsolete', "
            "  'generalizes perfectly to any domain')\n"
            "- Use hedged academic phrasing so it sneaks past casual review\n"
            "- Be specific to the topic: {topic}\n"
            "Output only the LaTeX sentence(s)."
        ).replace("{topic}", topic)},
    ]


def _contradiction_prompt(topic: str, section1: str, snippet1: str, section2: str, snippet2: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"Paper topic: {topic}\n\n"
            f"Section A ({section1}) opening: {snippet1[:300]}\n\n"
            f"Section B ({section2}) opening: {snippet2[:300]}\n\n"
            "Generate a pair of contradictory claims — one for each section — that directly "
            "conflict with each other. Requirements:\n"
            "- Each claim should be 1–2 sentences\n"
            "- They must contradict a specific factual aspect (e.g. model size, supervision type, "
            "  hardware requirements, training data, convergence properties)\n"
            "- Both must sound completely natural and authoritative in their respective sections\n"
            "- The contradiction must be specific to the paper topic\n\n"
            "Respond in this EXACT format (two lines, no extra text):\n"
            "CLAIM_A: <LaTeX sentence(s) for section A>\n"
            "CLAIM_B: <LaTeX sentence(s) for section B>"
        )},
    ]


# ── Record dataclass ──────────────────────────────────────────────────────────

@dataclass
class HallucinationRecord:
    type: str
    location: str
    severity: str
    detail: str


# ── Main engine ───────────────────────────────────────────────────────────────

class HallucinationEngine:
    def __init__(self, types: list, auto_mode: bool = False):
        self.types = types
        self.auto_mode = auto_mode
        self.records: list[HallucinationRecord] = []
        self._client = None
        self._topic = "research"
        self._model = "llama3-70b-8192"

        if auto_mode:
            self.types = random.sample(
                ["Fabrication", "Distortion", "Contradiction"],
                k=random.randint(2, 3)
            )

    def set_client(self, client, topic: str, model: str = "llama3-70b-8192"):
        """Must be called before inject_sections() to provide the Groq client."""
        self._client = client
        self._topic = topic
        self._model = model

    def _llm(self, messages: list, max_tokens: int = 600) -> str:
        if self._client is None:
            raise RuntimeError("HallucinationEngine: call set_client() before injecting.")
        return self._client.complete(
            messages=messages,
            model=self._model,
            max_tokens=max_tokens,
            temperature=0.85,
        )

    def _record(self, type_, location, severity, detail):
        self.records.append(HallucinationRecord(
            type=type_, location=location, severity=severity, detail=detail
        ))

    # ── Fabrication ───────────────────────────────────────────────────────────

    def _inject_fabricated_citation(self, content: str, location: str) -> str:
        msgs = _fabrication_citation_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=300).strip()
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Fabrication (fake citation + dataset)", location, "High",
            f"LLM-generated fake citation injected into {location}: {payload[:120]}..."
        )
        return injected

    def _inject_fabricated_table(self, content: str, location: str) -> str:
        msgs = _fabrication_results_prompt(self._topic, location)
        payload = self._llm(msgs, max_tokens=500).strip()
        # Ensure it's wrapped in table env if LLM missed it
        if not payload.startswith("\\begin{table}"):
            payload = (
                "\\begin{table}[h]\n\\centering\n"
                f"\\caption{{Fabricated comparison results on {self._topic}.}}\n"
                + payload +
                "\n\\label{tab:fabricated_llm}\n\\end{table}"
            )
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Fabrication (fake results table)", location, "High",
            f"LLM-generated fabricated results table in {location}."
        )
        return injected

    def _inject_fabricated_ablation(self, content: str, location: str) -> str:
        msgs = _fabrication_fake_experiment_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=300).strip()
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Fabrication (fake ablation study)", location, "High",
            f"LLM-generated fake ablation in {location}: {payload[:120]}..."
        )
        return injected

    # ── Distortion ────────────────────────────────────────────────────────────

    def _inject_distorted_numbers(self, content: str, location: str) -> str:
        msgs = _distortion_numbers_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=200).strip()
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Distortion (impossible numbers)", location, "Medium",
            f"LLM-generated numeric distortion in {location}: {payload[:120]}..."
        )
        return injected

    def _inject_overgeneralization(self, content: str, location: str) -> str:
        msgs = _distortion_overgeneralization_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=200).strip()
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Distortion (overgeneralization)", location, "Medium",
            f"LLM-generated overgeneralization in {location}: {payload[:120]}..."
        )
        return injected

    # ── Contradiction ─────────────────────────────────────────────────────────

    def _inject_contradiction(self, sections: dict) -> dict:
        """Generate a contradiction pair and place each half in the appropriate section."""
        s_keys = list(sections.keys())

        # Pick two different sections
        candidates_a = [s for s in s_keys if s in ("abstract", "intro", "method")]
        candidates_b = [s for s in s_keys if s in ("results", "conclusion", "experiments")]
        sec_a = candidates_a[0] if candidates_a else s_keys[0]
        sec_b = candidates_b[-1] if candidates_b else s_keys[-1]
        if sec_a == sec_b and len(s_keys) > 1:
            sec_b = s_keys[-1]

        msgs = _contradiction_prompt(
            self._topic,
            sec_a, sections[sec_a],
            sec_b, sections[sec_b],
        )
        raw = self._llm(msgs, max_tokens=300).strip()

        # Parse the structured response
        claim_a, claim_b = "", ""
        for line in raw.splitlines():
            if line.startswith("CLAIM_A:"):
                claim_a = line[len("CLAIM_A:"):].strip()
            elif line.startswith("CLAIM_B:"):
                claim_b = line[len("CLAIM_B:"):].strip()

        # Fallback if parsing fails
        if not claim_a or not claim_b:
            lines = [l for l in raw.splitlines() if l.strip()]
            claim_a = lines[0] if lines else "Our model is parameter-efficient with 12M parameters."
            claim_b = lines[1] if len(lines) > 1 else "Our model uses 47B parameters trained on 2T tokens."

        sections[sec_a] = sections[sec_a] + f"\n\n{claim_a}\n"
        sections[sec_b] = sections[sec_b] + f"\n\n{claim_b}\n"

        self._record(
            "Contradiction", f"{sec_a} \u2194 {sec_b}", "High",
            f"LLM-generated contradiction:\n  [{sec_a}]: {claim_a[:80]}...\n  [{sec_b}]: {claim_b[:80]}..."
        )
        return sections

    # ── Main entry point ──────────────────────────────────────────────────────

    def inject_sections(self, sections: dict) -> dict:
        """Apply LLM-generated hallucinations to sections dict."""
        result = dict(sections)
        s_keys = list(result.keys())

        if "Fabrication" in self.types:
            # Fake citation paragraph
            t1 = random.choice(s_keys)
            result[t1] = self._inject_fabricated_citation(result[t1], t1)

            # Fake results table in experiments/results
            t2 = next(
                (k for k in s_keys if k in ("experiments", "results")),
                random.choice(s_keys)
            )
            result[t2] = self._inject_fabricated_table(result[t2], t2)

            # Fake ablation study
            t3 = next(
                (k for k in s_keys if k in ("results", "experiments", "method")),
                random.choice(s_keys)
            )
            result[t3] = self._inject_fabricated_ablation(result[t3], t3)

        if "Distortion" in self.types:
            t = random.choice(s_keys)
            result[t] = self._inject_distorted_numbers(result[t], t)
            t2 = random.choice(s_keys)
            result[t2] = self._inject_overgeneralization(result[t2], t2)

        if "Contradiction" in self.types:
            result = self._inject_contradiction(result)

        return result

    def get_report(self) -> list[dict]:
        return [
            {
                "type": r.type,
                "location": r.location,
                "severity": r.severity,
                "detail": r.detail,
            }
            for r in self.records
        ]
