"""
hallucination_engine.py
ALL hallucination content is generated by the LLM at runtime.

FIXES vs original:
- _inject_fabricated_table: the fallback table wrapper was missing \\centering
  and the tabular environment itself — now wraps correctly.
- _fabrication_results_prompt: f-string used {section_key} inside the prompt
  but the prompt was a plain string, not an f-string → label was literal text
  "tab:fab_{section_key}". Fixed to use proper f-string interpolation.
- _inject_contradiction: CLAIM_A / CLAIM_B parsing was fragile (only looked at
  startswith on individual lines). Added multi-line fallback parser.
- inject_sections: added guard so empty LLM responses don't corrupt sections.
- All _llm() return values are stripped and checked for emptiness before use.
- HallucinationEngine.set_client: default model updated to match actual Groq IDs.
- Fabricated table: if LLM returns content that already has \\begin{table},
  the wrapper is skipped correctly (was broken due to strip() order).
"""

import random
from dataclasses import dataclass

# ── System prompt ─────────────────────────────────────────────────────────────
_HALLUCINATION_SYSTEM = (
    "You are an adversarial AI safety researcher. Your ONLY task is to generate "
    "realistic-looking but DELIBERATELY INCORRECT academic content to be injected "
    "into a LaTeX research paper. The content must read as legitimate, rigorous "
    "academic writing, yet contain fabricated citations, impossible numbers, "
    "overgeneralizations, or contradictions.\n\n"
    "CRITICAL RULES:\n"
    "1. Output ONLY valid LaTeX – no markdown fences (```), no explanatory text, "
    "   no prefixes like 'Sure, here is...'.\n"
    "2. The injected text must seamlessly continue from the provided section snippet.\n"
    "3. Be specific to the given paper topic – use domain terminology.\n"
    "4. If the prompt asks for a table, output a COMPLETE \\begin{table}...\\end{table}.\n"
    "5. If the prompt asks for a paragraph, output plain LaTeX text (may include \\cite, \\ref).\n"
    "6. Never break the LaTeX syntax – escape % signs as \\%, etc.\n"
    "7. Do NOT include any meta-commentary like 'Here is a fabricated citation:'.\n"
    "8. Do NOT output \\documentclass, \\begin{document}, or any preamble commands."
)


# ── Prompt builders ───────────────────────────────────────────────────────────

def _fabrication_citation_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n"
            f"TARGET SECTION: {section_key}\n"
            f"EXISTING TEXT (first 400 chars):\n{section_snippet[:400]}\n\n"
            "TASK: Generate a 2-3 sentence paragraph that fabricates a citation and a dataset.\n"
            "REQUIREMENTS:\n"
            "- Invent a plausible author name and year, e.g., 'Chen et al. (2024)'.\n"
            "- Invent a non-existent but convincing benchmark dataset with realistic stats.\n"
            "- Claim that this work validates our approach OR serves as our evaluation baseline.\n"
            "- Write in smooth academic prose that naturally follows the provided snippet.\n"
            "- Do NOT use LaTeX \\cite commands – write the citation as plain text.\n"
            "OUTPUT FORMAT: Only the LaTeX paragraph – no \\section, no extra text."
        )},
    ]


def _fabrication_results_prompt(topic: str, section_key: str) -> list[dict]:
    # FIX: was a plain string with {section_key} literal — now uses f-string
    label = f"tab:fab_{section_key}"
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n"
            f"TARGET SECTION: {section_key}\n\n"
            "TASK: Generate a complete LaTeX table with fabricated results.\n"
            "REQUIREMENTS:\n"
            f"- Full table environment: \\begin{{table}}[t] ... \\end{{table}}\n"
            "- Caption: realistic but containing subtly impossible numbers.\n"
            "- Include 4-6 baseline methods with realistic names (e.g., 'ResNet-152', 'ViT-L/16').\n"
            "- Our method: show implausibly large gains (e.g., +8.3% accuracy, 99.1% vs baselines 78-82%).\n"
            "- Use booktabs: \\toprule, \\midrule, \\bottomrule.\n"
            "- At least 3 metrics.\n"
            f"- Label: \\label{{{label}}}\n"
            "- Make method/metric names topic-specific.\n"
            "OUTPUT FORMAT: Only the complete LaTeX table environment – no extra text."
        )},
    ]


def _fabrication_fake_experiment_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n"
            f"TARGET SECTION: {section_key}\n"
            f"EXISTING TEXT (first 400 chars):\n{section_snippet[:400]}\n\n"
            "TASK: Generate a paragraph describing a fake ablation study.\n"
            "REQUIREMENTS:\n"
            "- Remove 2-3 components of 'our method' and report numeric drops that are too clean.\n"
            "- Reference a non-existent table: Table~\\ref{tab:ablation_fabricated}.\n"
            "- Conclude that each component is 'essential' or 'critical'.\n"
            "- Write in academic prose specific to the topic.\n"
            "OUTPUT FORMAT: Only the LaTeX paragraph – no section heading."
        )},
    ]


def _distortion_numbers_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n"
            f"TARGET SECTION: {section_key}\n"
            f"EXISTING TEXT (first 400 chars):\n{section_snippet[:400]}\n\n"
            "TASK: Generate 1-2 sentences with numerically distorted claims.\n"
            "The distortion must be subtle enough to pass a quick read but clearly wrong on inspection.\n"
            "EXAMPLES:\n"
            "- 'Our method achieves a 847\\% improvement over the baseline.'\n"
            "- 'The model converges in just 0.3 gradient steps.'\n"
            "- 'We evaluate on 47 out of 3 benchmarks.'\n"
            "Make the distortion specific to the paper topic.\n"
            "OUTPUT FORMAT: Only the LaTeX sentence(s) – no extra text."
        )},
    ]


def _distortion_overgeneralization_prompt(topic: str, section_key: str, section_snippet: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n"
            f"TARGET SECTION: {section_key}\n"
            f"EXISTING TEXT (first 400 chars):\n{section_snippet[:400]}\n\n"
            "TASK: Generate 2-3 sentences with a severe overgeneralization.\n"
            "REQUIREMENTS:\n"
            "- Sound confident and cite results (e.g., 'as shown by Smith et al. (2023)').\n"
            "- Make a sweeping, unjustified claim (e.g., 'solves X entirely', 'renders all prior work obsolete').\n"
            "- Use hedged academic phrasing ('These results strongly suggest...', 'It is evident that...').\n"
            "- Do NOT use LaTeX \\cite commands – write citations as plain text.\n"
            "OUTPUT FORMAT: Only the LaTeX sentence(s)."
        )},
    ]


def _contradiction_prompt(topic: str, section1: str, snippet1: str, section2: str, snippet2: str) -> list[dict]:
    return [
        {"role": "system", "content": _HALLUCINATION_SYSTEM},
        {"role": "user", "content": (
            f"PAPER TOPIC: {topic}\n\n"
            f"SECTION A ({section1}) opening:\n{snippet1[:300]}\n\n"
            f"SECTION B ({section2}) opening:\n{snippet2[:300]}\n\n"
            "TASK: Generate a pair of contradictory claims – one for each section.\n"
            "REQUIREMENTS:\n"
            "- Each claim: 1-2 sentences.\n"
            "- They must directly contradict a specific factual aspect "
            "(e.g., model size, supervision type, hardware requirements, training data size).\n"
            "- Both must sound completely natural in their respective sections.\n"
            "- Specific to the paper topic.\n"
            "OUTPUT FORMAT (EXACT – two lines only, no extra text):\n"
            "CLAIM_A: <LaTeX sentence(s) for SECTION A>\n"
            "CLAIM_B: <LaTeX sentence(s) for SECTION B>"
        )},
    ]


# ── Record dataclass ──────────────────────────────────────────────────────────

@dataclass
class HallucinationRecord:
    type: str
    location: str
    severity: str
    detail: str


# ── Main engine ───────────────────────────────────────────────────────────────

class HallucinationEngine:
    def __init__(self, types: list, auto_mode: bool = False):
        self.types    = list(types)
        self.auto_mode = auto_mode
        self.records: list[HallucinationRecord] = []
        self._client = None
        self._topic  = "research"
        self._model  = "llama-3.1-8b-instant"

        if auto_mode:
            self.types = random.sample(
                ["Fabrication", "Distortion", "Contradiction"],
                k=random.randint(2, 3)
            )

    def set_client(self, client, topic: str, model: str = "llama-3.1-8b-instant"):
        self._client = client
        self._topic  = topic
        self._model  = model

    def _llm(self, messages: list, max_tokens: int = 600) -> str:
        if self._client is None:
            raise RuntimeError("HallucinationEngine: call set_client() before injecting.")
        result = self._client.complete(
            messages=messages,
            model=self._model,
            max_tokens=max_tokens,
            temperature=0.85,
        )
        return (result or "").strip()

    def _record(self, type_, location, severity, detail):
        self.records.append(HallucinationRecord(
            type=type_, location=location, severity=severity, detail=detail
        ))

    # ── Fabrication ───────────────────────────────────────────────────────────

    def _inject_fabricated_citation(self, content: str, location: str) -> str:
        msgs    = _fabrication_citation_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=300)
        if not payload:
            return content
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Fabrication (fake citation + dataset)", location, "High",
            f"LLM-generated fake citation in {location}: {payload[:120]}..."
        )
        return injected

    def _inject_fabricated_table(self, content: str, location: str) -> str:
    msgs    = _fabrication_results_prompt(self._topic, location)
    payload = self._llm(msgs, max_tokens=600)
    if not payload:
        return content

    # Clean potential markdown or extra spaces
    payload = payload.strip()
    # If LLM gave a full table, extract just the tabular part
    if "\\begin{tabular}" in payload:
        import re
        match = re.search(r'(\\begin{tabular}.*?\\end{tabular})', payload, re.DOTALL)
        if match:
            payload = match.group(1)
    # Ensure it starts with \begin{tabular}
    if not payload.startswith("\\begin{tabular}"):
        # Fallback to a safe, minimal table
        payload = (
            "\\begin{tabular}{lccc}\n"
            "\\toprule\n"
            "Method & Acc & F1 & AUC \\\\\n"
            "\\midrule\n"
            "Baseline & 72.3 & 68.1 & 70.2 \\\\\n"
            "Ours & 99.1 & 98.7 & 98.9 \\\\\n"
            "\\bottomrule\n"
            "\\end{tabular}"
        )
    else:
        # Validate: count columns in first row (simple heuristic)
        lines = payload.split('\n')
        col_count = None
        for line in lines:
            if '\\tabular' in line:
                # extract column spec e.g., {lccc}
                spec_match = re.search(r'\{([lcrp@]+)\}', line)
                if spec_match:
                    col_count = len(spec_match.group(1))
                break
        if col_count and col_count > 0:
            # Check if any data row has different number of & separators
            pass  # optional deeper validation
        # else assume valid

    # Build complete table environment
    label = f"tab:fabricated_{location}"
    table_env = (
        f"\\begin{{table}}[t]\n"
        f"\\centering\n"
        f"\\caption{{Fabricated comparison results on {self._topic}.}}\n"
        f"\\label{{{label}}}\n"
        f"{payload}\n"
        f"\\end{{table}}"
    )
    injected = content + f"\n\n{table_env}\n"
    self._record(..., detail=f"LLM-generated table in {location}.")
    return injected

    def _inject_fabricated_ablation(self, content: str, location: str) -> str:
        msgs    = _fabrication_fake_experiment_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=300)
        if not payload:
            return content
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Fabrication (fake ablation study)", location, "High",
            f"LLM-generated fake ablation in {location}: {payload[:120]}..."
        )
        return injected

    # ── Distortion ────────────────────────────────────────────────────────────

    def _inject_distorted_numbers(self, content: str, location: str) -> str:
        msgs    = _distortion_numbers_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=200)
        if not payload:
            return content
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Distortion (impossible numbers)", location, "Medium",
            f"LLM-generated numeric distortion in {location}: {payload[:120]}..."
        )
        return injected

    def _inject_overgeneralization(self, content: str, location: str) -> str:
        msgs    = _distortion_overgeneralization_prompt(self._topic, location, content)
        payload = self._llm(msgs, max_tokens=200)
        if not payload:
            return content
        injected = content + f"\n\n{payload}\n"
        self._record(
            "Distortion (overgeneralization)", location, "Medium",
            f"LLM-generated overgeneralization in {location}: {payload[:120]}..."
        )
        return injected

    # ── Contradiction ─────────────────────────────────────────────────────────

    def _inject_contradiction(self, sections: dict) -> dict:
        """Generate a contradiction pair and place each half in the appropriate section."""
        s_keys = list(sections.keys())

        candidates_a = [s for s in s_keys if s in ("abstract", "intro", "method")]
        candidates_b = [s for s in s_keys if s in ("results", "conclusion", "experiments")]
        sec_a = candidates_a[0] if candidates_a else s_keys[0]
        sec_b = candidates_b[-1] if candidates_b else s_keys[-1]
        if sec_a == sec_b and len(s_keys) > 1:
            sec_b = s_keys[-1]

        msgs = _contradiction_prompt(
            self._topic,
            sec_a, sections[sec_a],
            sec_b, sections[sec_b],
        )
        raw = self._llm(msgs, max_tokens=300)

        # FIX: more robust CLAIM_A / CLAIM_B extraction
        claim_a, claim_b = "", ""
        for line in raw.splitlines():
            stripped_line = line.strip()
            if stripped_line.upper().startswith("CLAIM_A:"):
                claim_a = stripped_line[len("CLAIM_A:"):].strip()
            elif stripped_line.upper().startswith("CLAIM_B:"):
                claim_b = stripped_line[len("CLAIM_B:"):].strip()

        # Fallback: use first two non-empty lines
        if not claim_a or not claim_b:
            non_empty = [l.strip() for l in raw.splitlines() if l.strip()]
            claim_a = non_empty[0] if non_empty else "Our model is parameter-efficient with 12M parameters."
            claim_b = non_empty[1] if len(non_empty) > 1 else "Our model uses 47B parameters trained on 2T tokens."

        if claim_a:
            sections[sec_a] = sections[sec_a] + f"\n\n{claim_a}\n"
        if claim_b:
            sections[sec_b] = sections[sec_b] + f"\n\n{claim_b}\n"

        self._record(
            "Contradiction", f"{sec_a} \u2194 {sec_b}", "High",
            f"LLM-generated contradiction:\n  [{sec_a}]: {claim_a[:80]}...\n  [{sec_b}]: {claim_b[:80]}..."
        )
        return sections

    # ── Main entry point ───────────────────────────────────────────────────────

    def inject_sections(self, sections: dict) -> dict:
        """Apply LLM-generated hallucinations to sections dict."""
        result = dict(sections)
        s_keys = list(result.keys())

        if "Fabrication" in self.types:
            t1 = random.choice(s_keys)
            new = self._inject_fabricated_citation(result[t1], t1)
            if new.strip():
                result[t1] = new

            t2 = next(
                (k for k in s_keys if k in ("experiments", "results")),
                random.choice(s_keys)
            )
            new = self._inject_fabricated_table(result[t2], t2)
            if new.strip():
                result[t2] = new

            t3 = next(
                (k for k in s_keys if k in ("results", "experiments", "method")),
                random.choice(s_keys)
            )
            new = self._inject_fabricated_ablation(result[t3], t3)
            if new.strip():
                result[t3] = new

        if "Distortion" in self.types:
            t = random.choice(s_keys)
            new = self._inject_distorted_numbers(result[t], t)
            if new.strip():
                result[t] = new

            t2 = random.choice(s_keys)
            new = self._inject_overgeneralization(result[t2], t2)
            if new.strip():
                result[t2] = new

        if "Contradiction" in self.types:
            result = self._inject_contradiction(result)

        return result

    def get_report(self) -> list[dict]:
        return [
            {
                "type": r.type,
                "location": r.location,
                "severity": r.severity,
                "detail": r.detail,
            }
            for r in self.records
        ]
